SELECT P.PRODUCT_ID, PRODUCT_NAME, PRICE*AMOUNT TOTAL_SALES
FROM FOOD_PRODUCT P JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AMOUNT
    FROM FOOD_ORDER
    WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
    GROUP BY PRODUCT_ID
    ) O
    ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID
