SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT(DISTINCT S.USER_ID) PUCHASED_USERS, 
    ROUND(COUNT(DISTINCT S.USER_ID)/ (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) PUCHASED_RATIO
FROM USER_INFO U JOIN ONLINE_SALE S ON U.USER_ID = S.USER_ID AND YEAR(U.JOINED) = 2021
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE)
