SELECT DISTINCT(A.CART_ID)
FROM CART_PRODUCTS A JOIN CART_PRODUCTS B ON A.CART_ID = B.CART_ID
WHERE (A.NAME = 'Milk' AND B.NAME = 'Yogurt')
    OR (A.NAME = 'Yogurt' AND B.NAME = 'Milk')
ORDER BY A.CART_ID
