SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES) TOTAL_SALES
FROM AUTHOR A 
    JOIN (
        SELECT B.BOOK_ID, CATEGORY, AUTHOR_ID, SUM(SALES)*PRICE SALES
        FROM BOOK_SALES S JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
        WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
        GROUP BY BOOK_ID
    ) B 
    ON A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;
