SELECT SCORE, EMP.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES EMP 
    JOIN (
        SELECT EMP_NO, SUM(SCORE) SCORE
        FROM HR_GRADE
        GROUP BY EMP_NO
        ORDER BY SCORE DESC
        LIMIT 1
        ) E 
    ON EMP.EMP_NO = E.EMP_NO
