SELECT A.USER_ID, NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) 전체주소, CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8, 4)) 전화번호
FROM USED_GOODS_USER A JOIN (
    SELECT USER_ID, COUNT(*) CNT
    FROM USED_GOODS_BOARD JOIN USED_GOODS_USER ON WRITER_ID = USER_ID
    GROUP BY WRITER_ID
    ) B ON A.USER_ID = B.USER_ID
WHERE CNT >= 3
ORDER BY A.USER_ID DESC
