SELECT H.FLAVOR
FROM FIRST_HALF H 
    JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL
        FROM JULY
        GROUP BY FLAVOR
    ) J
    ON H.FLAVOR = J.FLAVOR
ORDER BY TOTAL_ORDER + TOTAL DESC
LIMIT 3
