SELECT A.APNT_NO, PT_NAME, P.PT_NO, D.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT A LEFT JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID AND D.MCDP_CD = 'CS'
                   LEFT JOIN PATIENT P ON  A.PT_NO = P.PT_NO 
WHERE DATE(APNT_YMD) = '2022-04-13'
    AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD
