SELECT CATEGORY, SUM(SALES) TOTAL_SALES
FROM BOOK B JOIN (
    SELECT BOOK_ID, SUM(SALES) SALES
    FROM BOOK_SALES
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY BOOK_ID
    ) S ON B.BOOK_ID = S.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY;
