SELECT CAR_ID, C.CAR_TYPE, ROUND(DAILY_FEE * (100 - DISCOUNT_RATE) * 0.01 * 30) FEE
FROM (
        SELECT CAR_ID, CAR_TYPE, DAILY_FEE
        FROM CAR_RENTAL_COMPANY_CAR
        WHERE CAR_ID NOT IN (
                SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
                )
            AND CAR_TYPE IN ('SUV', '세단')
    ) C 
    LEFT JOIN (
        SELECT CAR_TYPE, DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE CAR_TYPE IN ('SUV', '세단') AND DURATION_TYPE LIKE '30일 이상'
    ) P
    ON C.CAR_TYPE = P.CAR_TYPE
WHERE 500000 <= ROUND(DAILY_FEE * (100 - DISCOUNT_RATE) * 0.01 * 30) 
    AND ROUND(DAILY_FEE * (100 - DISCOUNT_RATE) * 0.01 * 30)  < 2000000
ORDER BY FEE DESC, C.CAR_TYPE, CAR_ID DESC
